name: Build and Deploy React App via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 📦 Install Node.js and Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use your Node.js version
      - run: npm install

      - name: 🔨 Build React App
        run: npm run build # Change this if your build command is different

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # Ensure this is correct
          server-dir: /public_html/projects.aaronweidele.com/sequence-master # Adjust your deployment path
